project_name: "dash-home"
release:
  prerelease: auto
  draft: false
before:
  hooks:
    - go mod download
    - make clean frontend statik
builds:
  - main: ./cmd/dash-home/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
    goarm:
      - 6
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
