env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
  project: "./tsconfig.json"
plugins:
  - react
  - '@typescript-eslint'
rules:
  # Extended Rules
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"

  # Custom Rules
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
