definitions:
  agent.Ambient:
    properties:
      humid:
        description: Humid - Humidity (percent)
        example: 50.3
        type: number
      last_fetch:
        description: LastFetch - Fetched date
        example: 2020-01-01 01:02:03 UTC
        type: string
      pressure:
        description: Pressure - Pressure (hpa)
        example: 1009.4
        type: number
      temp:
        description: Temp - Temperature (celsius)
        example: 27.5
        type: number
    type: object
  models.Room:
    properties:
      agent_id:
        description: AgentID - Agent ID (UUID)
        example: 16e88664-bf38-11ea-afc8-acde48001122
        type: string
      id:
        description: ID - Room ID
        type: string
      name:
        description: 'Name - Room name (ex: `john''s room`)'
        example: john's room
        type: string
      owner:
        description: 'Owner - Room owner (ex: `john doe`)'
        example: john doe
        type: string
    type: object
  server.CreateRoomRequest:
    properties:
      name:
        example: john's room
        type: string
    type: object
  server.UpdateAgentRequest:
    properties:
      address:
        example: localhost:8081
        type: string
    required:
    - address
    type: object
  storage.Agent:
    properties:
      address:
        description: Address - Agent Address (ex. `localhost:8081`)
        example: localhost:8081
        type: string
      id:
        default: <UNIQUE_ID>
        description: ID - Agent ID
        type: string
      online:
        description: Online - Check online
        type: boolean
    required:
    - address
    type: object
  storage.Room:
    properties:
      id:
        description: ID - Room ID
        type: string
      name:
        description: 'Name - Room name (ex: `john''s room`)'
        example: john's room
        type: string
      remotes:
        description: Remotes - Remote IDs
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Dash-Home API
  version: "1.0"
paths:
  /api/v1/agent:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Agent'
      summary: Get Agent entry
      tags:
      - agent
    post:
      consumes:
      - application/json
      parameters:
      - description: Add new agent
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/server.UpdateAgentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Agent'
      summary: Add Agent entry
      tags:
      - agent
  /api/v1/agent/sensors:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/agent.Ambient'
      summary: Get Sensors status form agent
      tags:
      - agent
  /api/v1/room:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Room'
      summary: Get Room entry
      tags:
      - room
    post:
      consumes:
      - application/json
      parameters:
      - description: Create new room
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/server.CreateRoomRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Room'
      summary: Craete Room entry
      tags:
      - room
  /healthz:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check API Response for Health Check
swagger: "2.0"
