definitions:
  models.Room:
    properties:
      id:
        description: ID - Room ID
        type: string
      name:
        description: 'Name - Room name (ex: `john''s room`)'
        example: john's room
        type: string
      owner:
        description: 'Owner - Room owner (ex: `john doe`)'
        example: john doe
        type: string
      status:
        $ref: '#/definitions/models.RoomStatus'
        description: Status - Room Status
        type: object
    type: object
  models.RoomStatus:
    properties:
      humid:
        description: Humid - Humidity (percent)
        example: 50.3
        type: number
      pressure:
        description: Pressure - Pressure (hpa)
        example: 1009.4
        type: number
      temp:
        description: Temp - Temperature (celsius)
        example: 27.5
        type: number
    type: object
  models.UpdateAgentRequest:
    properties:
      address:
        description: Address - Agent Address (ex. `localhost:8081`)
        example: localhost:8081
        type: string
    required:
    - address
    type: object
  storage.Agent:
    properties:
      address:
        description: Address - Agent Address (ex. `localhost:8081`)
        example: localhost:8081
        type: string
      id:
        default: <UNIQUE_ID>
        description: ID - Agent ID
        type: string
      online:
        description: Online - Check online
        type: boolean
    type: object
info:
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Dash-Home API
  version: "1.0"
paths:
  /api/v1/agent:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Agent'
      summary: Get Agent entry
      tags:
      - agent
    post:
      consumes:
      - application/json
      parameters:
      - description: Add new agent
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/models.UpdateAgentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Agent'
      summary: Add Agent entry
      tags:
      - agent
  /api/v1/room:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Room'
      summary: Get Room entry
      tags:
      - room
  /healthz:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check API Response for Health Check
swagger: "2.0"
