name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - name: Make binaries
        run: make clean frontend build
