name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - name: Run Go Releaser (Snapshot)
        uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist --snapshot

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dash-home
          path: dist/*
