name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - name: Make binaries
        run: make clean frontend build
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prelease: false
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: dash-home_linux_amd64
          asset_path: ./build/linux_amd64/dash-home
